requires 'Mojolicious' => '5.37';
requires 'Mojolicious::Plugin::Recaptcha';
requires 'Mojolicious::Plugin::Mail';
requires 'Mojolicious::Plugin::Gravatar';
requires 'Mojolicious::Plugin::CSRFDefender';

requires 'Moose';
requires 'DBI';

requires 'Class::Load';
requires 'Crypt::Blowfish';
requires 'Crypt::Simple';
requires 'Data::Serializer';
requires 'Data::UUID';
requires 'DBD::mysql';
requires 'Digest::SHA2';
requires 'Email::Valid';
requires 'File::Slurp';
requires 'HTML::Entities';
requires 'JSON';
requires 'List::MoreUtils';
requires 'Params::Util';
requires 'Text::CSV';
requires 'Try::Tiny';
requires 'Validate::Tiny';
requires 'Hash::Storage';
requires 'Query::Abstract';
requires 'Hash::Storage::Driver::DBI';
requires 'experimental';

# for Net::Amazon::S3:
requires 'Data::Stream::Bulk::Callback';
requires 'DateTime::Format::HTTP';
requires 'Digest::HMAC_SHA1';
requires 'Digest::MD5';
requires 'Digest::MD5::File';
requires 'File::Find::Rule';
requires 'File::stat';
requires 'Getopt::Long';
requires 'HTTP::Date';
requires 'HTTP::Status';
requires 'IO::File';
requires 'LWP::UserAgent::Determined';
requires 'MIME::Base64';
requires 'MIME::Types';
requires 'Moose::Util::TypeConstraints';
requires 'MooseX::StrictConstructor';
requires 'MooseX::Types::DateTime::MoreCoercions';
requires 'Path::Class';
requires 'Pod::Usage';
requires 'Regexp::Common';
requires 'Term::Encoding';
requires 'Term::ProgressBar::Simple';
requires 'URI';
requires 'URI::Escape';
requires 'URI::QueryParam';
requires 'XML::LibXML';
requires 'XML::LibXML::XPathContext';